on_gpu: False

epochs: 100
learning_rate: 0.1
momentum: 0.9
batch_size: 1

job_id: -1

pin_memory: True
num_workers_dataloader: 0
set_gradients_none: False
fp16: False
allow_tf32: False

master_addr: localhost
master_port:
device:

min_checkpoint_epoch: 10
min_checkpoint_epoch_dist: 0

root_dir: ''
checkpoint_path: ''
model_save_path: ''
