# general
on_gpu: False
job_id: -1

# logging
wandb: True
wandb_project: 'carQUEST-ML'
wandb_group: ''
wandb_watch_model: False
verbose: True

# training hyperparameters
epochs: 500
learning_rate: 0.002
momentum: 0.9
batch_size: 16

# model parameters
hidden_size: 64
layers: 2

# training configuration
set_gradients_none: False
fp16: False
allow_tf32: False

# dataloader parameters
shuffle: True
drop_last: True
pin_memory: True
num_workers_dataloader: 0

# data
processes: 0
jobs: 0

# distributed training
master_addr: localhost
master_port:
device:

# model checkpoint
min_checkpoint_epoch: 10
min_checkpoint_epoch_dist: 0

# model save
save_model: False

# paths
base_path: ''
data_path: ''
checkpoint_path: ''
model_save_path: ''
