# general
gpu: False
world_size: 1
job_id: 1
seed: 0

# logging
wandb: True
wandb_project: 'carQUEST-ML'
wandb_group: ''
wandb_watch_model: False
wandb_table_name: 'data_table'
wandb_table_elements: 5
verbose: True
float_precision: 6
log_to_file: False

# training hyperparameters
epochs: 50
learning_rate: 0.01
momentum: 0.9
batch_size: 16
lambda: 1.0

# learning rate scheduler
lr_scheduler_factor: 0.1
lr_scheduler_patience: 3

# training configuration
stepwise: False
set_gradients_none: False
fp16: False
allow_tf32: False

# dataloader parameters
shuffle: True
drop_last: True
pin_memory: True
num_workers_dataloader: 0

# data
pickle_file_name: da.pkl
processes: 0
jobs: 0
scaling_factor: 1
reduction_factor: 0.9
accumulation_window: 1
offset: 1
only_process: False
enhances: 0
enhance_base_lambda: 1.0
enhance_lambda_variability: 0.1

# distributed training
master_addr: localhost
master_port:
device:

# model checkpoint
min_checkpoint_epoch: 10
min_checkpoint_epoch_dist: 0

# save/load
save: True
load: False
save_model: True
load_model: False
save_datasets: False
load_datasets: False

# paths
base_path: ''
data_path: ''
save_dir: ''
ds_save_path: ''
ds_load_path: ''
checkpoint_file: 'checkpoint.pt'
checkpoint_save_path: ''
checkpoint_load_path: ''
model_file: 'model.pt'
model_save_path: ''
model_load_path: ''
system_config_path: ''
graph_description_path: ''
output_file: ''
