type: object
required:
  - jobCount
properties:
  jobCount:
    type: integer
    description: Number of Jobs in the System
  branchingFactor:
    type: object
    description: Branching factor, normally distributed over the given range
    properties:
      min:
        type: integer
        default: 1
        description: Minimum branching factor
      max:
        type: integer
        default: 1
        description: Maximum branching factor
  length:
    type: integer
    description: Length of the shortest path in the system from start to finish
  processCount:
    type: integer
    description: Total number of processes
